version: '3.8'
services:
  api:
    container_name: docker-demo-api
    build:
      context: ./API
      # dockerfile: dockerfile.prod #trỏ tới dockerfile
      # target: build               #trỏ tới stage trong dockerfile
      # mặc định ko khai báo sẽ tự lấy dockerfile và build
    image: docker-demo-api:dev
    ports:
      - "7000:5000"
    volumes:
      - "./API:/home/app"

  spa:
    container_name: docker-demo-spa
    build:
      context: ./SPA
      # tương tự ở trên
    image: docker-demo-spa:dev
    ports:
      # - "5000:80"   #prod
      - "8000:4200" #dev
    volumes:
      - "./SPA/src:/app/src"