FROM node:14-alpine as build
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app/
RUN yarn install
COPY . /app/
RUN yarn build

FROM nginx:1.17.1-alpine as deploy
COPY --from=build /app/dist/ /usr/share/nginx/html/