FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build 
WORKDIR /home/app
COPY DockerDemo.csproj .
RUN dotnet restore DockerDemo.csproj --disable-parallel
COPY . .
RUN dotnet publish DockerDemo.csproj -o /publish/

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as deploy
WORKDIR /publish
COPY --from=build /publish .
# https://www.abhith.net/blog/docker-sql-error-on-aspnet-core-alpine/
RUN apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV ASPNETCORE_URLS="http://+:6000"
ENTRYPOINT ["dotnet", "DockerDemo.dll"]